'use strict';
const $=id=>document.getElementById(id);let state=null,role='owner',selected='1',privateView=false,view='unseen',blob=null,epoch=0,currentKey='',busy=false;
function clearOriginal(){epoch++;$('original').hidden=true;$('original').removeAttribute('src');$('fullHelp').hidden=true;if(blob)URL.revokeObjectURL(blob);blob=null;currentKey='';}
async function api(path,options={}){const response=await fetch(path,{cache:'no-store',credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.method==='POST'&&state?.csrf?{'X-CSRF-Token':state.csrf}:{}),...options.headers}});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
async function refresh(reset=false){try{state=await api('/api/state');if(!state.owner){role='visitor';privateView=false;}if(reset){privateView=false;view='unseen';}render();}catch(e){clearOriginal();$('holo').hidden=true;$('message').textContent='Connection unavailable. Originals are hidden. Retry by reloading.';}}
function render(){if(!state)return;const a=state.assets.find(x=>x.id===selected),owner=state.owner&&role==='owner';
$('account').textContent=state.owner?'Signed in to isolated test account':'Visitor · no owner access';$('roles').hidden=!state.owner;$('logout').hidden=!state.owner;$('showLogin').hidden=state.owner;$('controls').hidden=!owner;$('ownerRole').setAttribute('aria-pressed',owner);$('visitorRole').setAttribute('aria-pressed',!owner);$('mode').value=a.mode;$('apply').disabled=state.mintLocked;$('private').disabled=state.mintLocked;
if(!owner)privateView=false;if(state.mintLocked||a.mode==='unseen'&&!privateView)view='unseen';if(a.mode==='seen'&&!privateView)view='seen';
const full=!state.mintLocked&&(privateView&&owner||view==='seen'&&a.mode!=='unseen');$('viewTitle').textContent=privateView?'Owner private view':owner?'Public listing preview':'Visitor view';$('permission').textContent=state.mintLocked?'Mint lock active · originals blocked':privateView?'Private original · public permission remains '+a.mode.toUpperCase():'Public permission: '+a.mode.toUpperCase();$('tabs').hidden=privateView||a.mode!=='both'||state.mintLocked;$('backPublic').hidden=!privateView;$('seen').setAttribute('aria-pressed',view==='seen');$('unseen').setAttribute('aria-pressed',view==='unseen');$('holo').hidden=full||selected!=='1';$('fixtureCover').hidden=full||selected!=='2';
if(full){const key=selected+':'+privateView+':'+role+':'+a.mode;if(currentKey!==key){clearOriginal();currentKey=key;showOriginal(key);}}else clearOriginal();}
async function showOriginal(key){const e=epoch;try{const url=(privateView?'/api/':'/api/visitor/')+'assets/'+selected+'/original';const r=await fetch(url,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw Error('Original blocked by server');const data=await r.blob();if(e!==epoch||currentKey!==key)return;blob=URL.createObjectURL(data);$('original').src=blob;$('original').hidden=false;$('fullHelp').hidden=false;}catch(err){if(e===epoch){clearOriginal();$('message').textContent=err.message;}}}
async function post(path,data){return api(path,{method:'POST',body:JSON.stringify(data)});}
async function action(fn){if(busy)return;busy=true;$('message').textContent='';try{await fn();}catch(e){$('message').textContent=e.message;}finally{busy=false;}}
$('asset').onchange=()=>{clearOriginal();selected=$('asset').value;privateView=false;view='unseen';$('probeResult').textContent='';$('savePanel').hidden=true;render();};
$('ownerRole').onclick=()=>{clearOriginal();role='owner';privateView=false;render();};$('visitorRole').onclick=()=>{clearOriginal();role='visitor';privateView=false;render();};
$('seen').onclick=()=>{view='seen';render();};$('unseen').onclick=()=>{view='unseen';render();};$('private').onclick=()=>{privateView=true;render();};$('backPublic').onclick=()=>{privateView=false;view='unseen';render();};
$('apply').onclick=()=>action(async()=>{const mode=$('mode').value;await post('/api/mode',{id:selected,mode});await refresh(true);$('message').textContent='Public permission saved.';});
$('lock').onclick=()=>action(async()=>{await post('/api/mint-lock',{locked:true});await refresh(true);});$('unlock').onclick=()=>action(async()=>{await post('/api/mint-lock',{locked:false});await refresh(true);});
$('showLogin').onclick=()=>{$('loginPanel').hidden=false;};
async function login(code){await post('/api/login',{code});$('code').value='';$('loginPanel').hidden=true;role='owner';await refresh(true);}
$('login').onclick=()=>action(()=>login($('code').value.trim()));$('logout').onclick=()=>action(async()=>{clearOriginal();await post('/api/logout',{});await refresh(true);});
$('probe').onclick=()=>action(async()=>{const r=await fetch('/api/visitor/assets/'+selected+'/original',{cache:'no-store',credentials:'same-origin'});if(r.ok){await r.body.cancel();$('probeResult').textContent='HTTP 200 · original available because public reveal is enabled.';}else $('probeResult').textContent='HTTP '+r.status+' · visitor did not receive the original.';});
window.addEventListener('pagehide',clearOriginal);window.addEventListener('pageshow',()=>refresh());document.addEventListener('visibilitychange',()=>{if(document.hidden)clearOriginal();else refresh();});
setInterval(()=>{if(!document.hidden&&!busy)refresh();},5000);
(async()=>{const params=new URLSearchParams(location.hash.slice(1)),code=params.get('owner');if(code){history.replaceState(null,'',location.pathname);await action(()=>login(code));}else await refresh();})();
