import {generateKeyPairSync,sign} from 'node:crypto';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {AccessGate,principalFor} from './access-gate.mjs';
const key=()=>{const k=generateKeyPairSync('ed25519');return {publicKey:k.publicKey.export({type:'spki',format:'pem'}),privateKey:k.privateKey};};
const alice=key(),bob=key();let now=100000,online=true,status='confirmed',revision=1,owner=principalFor(alice.publicKey),stale=false;
// This authority is a deliberately fake ledger. Never deploy as ownership proof.
const authority={current:asset=>{if(!online)throw Error('offline');return asset==='demo:1'?{owner,revision:String(revision),status,checkedAt:now-(stale?11000:0)}:null;}};
const gate=new AccessGate({authority,origin:'https://isolated-test.invalid',clock:()=>now});
const results=[];const check=(name,fn)=>{fn();results.push({name,passed:true});};
const login=k=>{const c=gate.challenge('demo:1',k.publicKey);return gate.login(c.nonce,sign(null,Buffer.from(c.message),k.privateKey));};
const a=login(alice);
check('Current owner can request original',()=>assert.equal(gate.originalAllowed('demo:1',a),true));
check('Visitor cannot request unrevealed original',()=>assert.equal(gate.originalAllowed('demo:1'),false));
check('Non-owner cannot establish asset session',()=>assert.throws(()=>login(bob)));
check('Session cannot access another asset',()=>assert.equal(gate.originalAllowed('demo:2',a),false));
check('Forged session denied',()=>assert.equal(gate.originalAllowed('demo:1','made-up'),false));
check('Wrong signing key rejected',()=>{const c=gate.challenge('demo:1',alice.publicKey);assert.throws(()=>gate.login(c.nonce,sign(null,Buffer.from(c.message),bob.privateKey)));});
check('Challenge replay rejected',()=>{const c=gate.challenge('demo:1',alice.publicKey),sig=sign(null,Buffer.from(c.message),alice.privateKey);gate.login(c.nonce,sig);assert.throws(()=>gate.login(c.nonce,sig));});
check('Expired challenge rejected',()=>{const c=gate.challenge('demo:1',alice.publicKey);now+=60001;assert.throws(()=>gate.login(c.nonce,sign(null,Buffer.from(c.message),alice.privateKey)));});
check('Owner can enable public reveal',()=>{gate.setReveal('demo:1',a,true);assert.equal(gate.originalAllowed('demo:1'),true);});
const outstanding=gate.challenge('demo:1',alice.publicKey);
owner=principalFor(bob.publicKey);revision++;
check('Transfer resets public reveal for new ownership revision',()=>assert.equal(gate.originalAllowed('demo:1'),false));
check('Former owner existing session denied after transfer',()=>assert.equal(gate.originalAllowed('demo:1',a),false));
check('Former owner cannot change reveal',()=>assert.throws(()=>gate.setReveal('demo:1',a,true)));
check('Pre-transfer signed challenge rejected',()=>assert.throws(()=>gate.login(outstanding.nonce,sign(null,Buffer.from(outstanding.message),alice.privateKey))));
const b=login(bob);
check('New owner gets private original access',()=>assert.equal(gate.originalAllowed('demo:1',b),true));
check('New owner controls public reveal',()=>{gate.setReveal('demo:1',b,true);assert.equal(gate.originalAllowed('demo:1'),true);gate.setReveal('demo:1',b,false);});
online=false;
check('Verifier outage blocks private access',()=>assert.equal(gate.originalAllowed('demo:1',b),false));
check('Verifier outage blocks permission mutation',()=>assert.throws(()=>gate.setReveal('demo:1',b,true)));
online=true;stale=true;
check('Stale ownership data denied',()=>assert.equal(gate.originalAllowed('demo:1',b),false));
stale=false;status='uncertain';
check('Uncertain chain state denied',()=>assert.equal(gate.originalAllowed('demo:1',b),false));
status='confirmed';owner=principalFor(alice.publicKey);revision++;
check('Return transfer does not revive old session',()=>assert.equal(gate.originalAllowed('demo:1',a),false));
const a2=login(alice);
check('Fresh proof after return transfer accepted',()=>assert.equal(gate.originalAllowed('demo:1',a2),true));
check('Logout invalidates session',()=>{gate.logout(a2);assert.equal(gate.originalAllowed('demo:1',a2),false);});
const a3=login(alice);now+=300001;
check('Session expiry enforced',()=>assert.equal(gate.originalAllowed('demo:1',a3),false));
writeFileSync(new URL('./results.json',import.meta.url),JSON.stringify({scope:'LOCAL SIMULATION: real Ed25519 signatures; fake ownership ledger; no Zcash wallet, proof, chain transfer or hosted integration',passed:results.length,results},null,2));
console.log(`${results.length} local simulation checks passed. Zcash verification remains unimplemented.`);
